<a href="https://colab.research.google.com/github/jasen8651/python001/blob/master/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
#https://github.com/rougier/numpy-100 문제
#numpy는 파이썬에서 산술 계산을 위한 가장 필수적인 패키지,
#numpy의 배열 객체를 데이터 교환을 위한  공통언어처럼 사용, 빠른 배열 계산과 유여한 브로드 캐스팅 기능제공
#반복문을 작성할 필요없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수, 배열 데이터를 디스크에 ㅆ거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구
#선형대수 난수 생성기등에 사용, c,c++포트란으로 작성한 코드를 연결항수있는 c apl제공

#!pip install numpy
import numpy as np

a =np.zeros(3)
a
print(type(a))
print(dir(a))
print(len(dir(a)))
print(a)


#처음 객체들은 type, dir을 해본다
print(type(a))
print(dir(a))


#1차원 배열 =백터
a = np.array([1,2,3])
a
#2차원 배열  = 행렬
b = np.array([[1,2],[3,4]])
b
#3차원 배열 이상 = 텐서
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

print(len(dir(c)))


#문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
a =np.array([1,'2',3])
print(a)
print(type(a))
print(type(a[0]))

b =np.array(['a',1, True])
print(b)
print(type(b))

c =np.array([1, True, 2, False])
print(c)

print(type(c[0]))




<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [6]:
#np.zeros : 튜플 인자를 넣으면 그대로 모양을 만든다, zeros는 0으로 값을 채운다,
a =np.zeros((2,3))
a =np.zeros([2,3])
a


c =np.zeros((2,3,2))
c

#np.eye : 단위행렬, 숫자만 사용
a = np.eye(3)#3행 3열을 생성
a
b = np.eye(3,2)#3행 2열을 생성
b
#eye는 행과 열을 지정가능 
c= np.eye(3,4,k=1)
c
#np.idenyity : 크기한개만 지정해서 생성
e =np.identity(3,2)
e

NameError: ignored

In [5]:
# np.full : 지정한 크기의 배열을 생성화고 채울값을 지정한다.
a= np.full((2,2),1)
a

b= np.full(3,4)
b

c = np.full((2,2), [1,2])
c

#np.empty : 배열을 생성하고 초기화을 지정하지 않는다,
a= np.empty(3)
a
#메모리에 있는 값이나 이전에 사용했던 값들로 채워짐

k = np.zeros((2,3))
k

b = np.empty((2,3))
b

c = np.empty((2,3))
c

#np.ones 배열의 값을 1로 초기화
a = np.ones(3)
a

b = np.ones([2,3])
b

c = np.empty((2,3))
c

e =np.eye(3,4)
e

d =np.empty((3,4))
d

f =np.empty((3,4))
f


##_like가 붙으면 shape이 같게 만들어짐, 연산하기 위해서 shape을 맞워야 하는 경우가 있다.
a = np.array([[1,2,3],[4,5,6]])
a

a.shape

b= np.empty_like(a)
b

c= np.eye(2)
c
c.shape

d= np.empty_like(a)
d

#linspace : 동등한 간격으로 값을 생성한다, 0~49까지 50개가 생성되면 num값이 생략되어 있으므로 start와 end까지 계산해서 defult 50이 생서linspace(start, end, num) => linspace(0,49) #num =50
a =np.linspace(0,49)
a
b =np.linspace(1,5)
b

len(b)

np.linspace(1,10,3)
#1~10까지 3개의 요소를 생성, 기본은 endoint=참으로 설정되어 있기 때문에 10이 포함
np.linspace(1,10,3, endpoint=False)
#1_100미만 사이에서 3개의 요소 생성, 거짓으로 설정되어 있으며 10이 포함안됨

#logspace 
np.logspace(1,50,10)

#*dtype : c기반으로 만들어짐 c의 데이터 타입 차용가능
a = np.array([1,2,3])
a
print(type(a))
print(a.dtype)

b = np.array([1,2,3], dtype=np.int8)
b

c=np.array([-127,-128, 17, 2, 3, -127, -128, 127], dtype=np.int8)
c

d =np.array([127,2,3, -127, -128], dtype=int)
d

type(d[0])

NameError: ignored

In [ ]:
help(sum)

a = np.array([[1,2,3], [4,5,6]])
a.shape
# 배열이 몇 차원인지 알려준다.
a.ndim
a.dtype
a.size
#d요소당 바이트 수를 알려줌
a.itemsize

#numpy 와 python 속도차이
np.arange(10)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#numpy 계산
%time np.sum(np.arange(1000000))
#파이썬 계산
%time sum(np.arange(1000000))

NameError: ignored

NameError: ignored

In [4]:
%time np.sum(range(1000))

NameError: ignored

In [7]:
#copy
#파이썬에서 카피할떼 
a = [1,2,3]
b=a 
b
a is b

b[0]=7
b
a
#a,b기 메모리를 공유


SyntaxError: ignored

In [ ]:

#listcopy : 카피는 값만 같고 메모리는 공유하지 않는다.
a = [1,2,3]
b =a.copy()
a is b
id(a)
id(b)
a ==b
b[0] = 8
print(a)
print(b)

#list가 2차원일떼 
a =[[1,2,3]]
type(a)
b=a.copy() 
print(a is b)
print(a==b)

print(a[0] is b[0])
print(a[0] == b[0])

import copy 
a=[[1,2,3]]
b =copy.deepcopy(a)

print(a)
print(b)


print(a[0] is b[0])
print(a[0] == b[0])
# :는 전체라는 뜻이다. 슬라이싱 방식으로 1차 리스트일때는 재할당하면  deepcopy가 된다. 슬라이싱 2차 리스트 이상인경우 shallo copy가 발생
a=[1,2,3]
b=a[:]
print(a is b)
print(a == b)
b[0]=7
print(a is b)
print(a == b)
#파이썬의 카피는 기본적으로 shallow copy를 하낟



a = b = np.array([1,2,3])
print(a is b)
print(a == b)

In [48]:
#numpy의 카피
a = b = np.array([1,2,3])
print(a is b)
print(a == b)

#array는 sepuence타입으로 인덱싱과 슬라리싱 가능
a[0]
a[:]

a[0] =100
print(a)
print(b)
#array는 homeogeneous, sequence, mutable이다
a = np.array([[1,2,3]])
b =a.copy()
print(a is b)
print(a[0]is b[0])

#a as 개열 : 다른 테이터 타입을 가져와서 바꿔서 사용할떼는 as라는 이름을 붙인다.
a =[1,2,3]
print(type(a))
print(type(a[0]))
b =np.array(a)
print(type(b))
print(type(b[0]))


a =[1,2,3]
print(type(a))
print(type(a[0]))
b =np.asarray(a)
print(type(b))
print(type(b[0]))

#float
a =[1,2,3]
print(type(a))
print(type(a[0]))
b =np.asfarray(a)
print(type(b))
print(type(b[0]))


True
[ True  True  True]
[100   2   3]
[100   2   3]
False
False
<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [70]:
#파이썬의 리스트 테이터 타입 float이면 floar ndarray
#파이썬 리스트 데이터 타입 int 면 int ndarry로 변환

a = [1.,2.,3.]
print(type(a))
print(type(a[0]))

b = np.asarray(a)
print(type(b))
print(type(b[0]))

c = np.array(a)
print(type(c))
print(type(c[0]))


# 값 가져오기
#, 
a = [[1,2,3,],[4,5,6]]
b =np.array([[1,2,3], [4,5,6]]) #numpy는 기본적으로 인덱싱/슬라이싱할때 콤마 사용
a[0]
a[slice(0,1)]
#슬라이스 함수를 이용해서 콤마를 사용하는 방법
a[slice(0,2)]
print(b[0,2])
print(a[0][2])
print(a[0][-1])
a =[[1,2,3,4,]]


b =np.array([1,2,3,4])
b

#원소별로 비교해서 참,거짓로 계산
b =[np.array([False, False, True, True])]

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
3
3
3


TypeError: ignored

In [ ]:
#numpy에서 boolean indexing조건 : array만 가능, numpy true, false로만 가능, shape이 맞아야한다.
a = [1,2,3,4]
a[True,True, False, False]

In [84]:
b = np.arange(100).reshape(20,5)
b[:]

b[1:3]
print(b[1:3,2:4])
print(b[[1,3,5]])
print(b[[1,3,5],[0,2,4]])
b[[1,3,4],[0,2,1]]
b[[1,3,4],[0,2]]

[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]


IndexError: ignored