<a href="https://colab.research.google.com/github/jasen8651/python001/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
#버전 확인
import sys
print(sys.version)#파이선

#numpy
np.__version__

!pip freeze



###파일 형식 데이터 불러오기

In [3]:
from google.colab import drive
drive.mount('/content/dirve')
%cd /content/dirve/MyDrive/python_demo

Mounted at /content/dirve
/content/dirve/MyDrive/python_demo


In [ ]:
data = pd.read_csv('pdsample/num.txt', header=None)
data
type(data)
data[0]

0    1
1    6
Name: 0, dtype: int64

In [ ]:
a =np.arange(12).reshape(3,4)
print(a)
print(a[1][2])
print(a[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]


In [ ]:
b = [[ 0 , 1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8 , 9, 10 ,11]]
print(b[1][2])


6


In [ ]:
#데이터 프레임에서 데이터 가져오기
print(data.iloc[0])
print(type(data.iloc[0]))


0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
print(data.values)
print(type(data.values))
data.values


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header='infer')
data

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
data.head()#맨위
data.tail()#맨아래


data.sample()
data.head(10) #숫자 지정하면 10개 가져옴
data.sample(10)

data.columns

dictdata ={'name':'홀길', 'age':'34'}
dictdata['name']
#pandas는 dictionary와 attribute방식 모두 가져옴
data['tip'][2]
data.tip

#data['tip',day]
data[['tip','day']]

data[1:3]


total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [ ]:
data.iloc[3]

#하나의 컬럼, 행을 가져오면 series로 리턴

type(data[['tip']])
data.iloc[[0,3,5]]

data.iloc[3][1]
data.iloc[0:3, 1:4]
data.iloc[[0,3,5],[1,4,5]]
#iloc는 indexrt을 이용해서 가져오고 loc를 이름을 이용해서 가져온다
data.loc[0,'tip'] #행은 이름이 성정되여 있지 않아서 자동으로 생성된 rangrk 

data.head()
data.loc[[0,3,5],['tip', 'day', 'time']]

#at : 이름으로 한 위치의 값만 가져온다
data.at[0, 'tip']
data.iloc[0, 1]
#data.at[0:3,'tip'] 슬라이싱 인덱싱 적용 불가
#data.at[[1,3,5],['tip','smokr','dat']] 인덱스만 가능 


1.01

##iat은 인넥스 번호로 한 위치의 값을 가져온다

In [ ]:
data.iat[0,1]

# 슬라이싱 사용불가능data.iat[0:3, 1]
data['tip']>5

data[data['tip']>=5]

data.tip
data['tip']

a = data[data['tip']>=5]
a['tip']

data[data['tip']>=5]. loc[:,'tip':'day']
data[data['tip']>=5]. iloc[:,1:5]



11      5.00
23      7.58
39      5.00
44      5.60
46      5.00
47      6.00
52      5.20
59      6.73
73      5.00
83      5.00
85      5.17
88      5.85
116     5.07
141     6.70
142     5.00
143     5.00
155     5.14
156     5.00
170    10.00
172     5.15
181     5.65
183     6.50
185     5.00
197     5.00
211     5.16
212     9.00
214     6.50
239     5.92
Name: tip, dtype: float64

In [ ]:
#요일이 sun이거나 sat의 tip과 day값가져오기
data[(data['day']=='Sun') | (data['day']=='Set')][['tip','day']]
a =data[(data['day']=='Sun') | (data['day']=='Set')]
a['day'].unique()
a[['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
186  3.50  Sun
187  2.00  Sun
188  3.50  Sun
189  4.00  Sun
190  1.50  Sun

[76 rows x 2 columns]

In [ ]:
len([1,2,3,])
len('123')
len({'a':1, 'b':2,'c':3})
len(data)

#[1,2,3].size 에러\/ '123'.size/
import numpy as np
(np.array([1,2,3])).size
data.size
data['tip'].size


244

In [ ]:
data2 =data.rename(mapper={'size':'size_'}, axis=1)
data2 = data.rename(columns={'size':'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

In [ ]:
#category : 문자열보다 많은 기능 가능, 문자, 숫자 가능, 몇개로 분류할 수 있을때 사용
data.info()

type(data['sex'])

print(data['sex'].dtype)


In [ ]:
# object를 category로 데이터 타입 변경
data['sex'] = data['sex'].astype('category')
data.info()

data.sample()
#data에서 여성의 데이터만 가져와라
#1data[data['sex']=='Female']
#data[data.sex=='Female']
data[data['sex']=='Female']['sex'].unique()
data[data.sex=='Female']['sex'].unique()
print('--------------------------------------')
#금요일에 온 여자만 가져와라
data['day'].unique()
#dictionary
data[(data['day']=='Fri') & (data['sex']=='Female')]
#attribute
data[(data.day=='Fri') & (data.sex=='Female')]

In [37]:
data[(data['day']=='Fri') & (data['sex']=='Female')]['sex'].unique()
data[(data.day=='Fri') & (data.sex=='Female')]['day'].unique()

array(['Fri'], dtype=object)

In [ ]:
#통계데이터 describe : 데이터가 숫자로 된 컬럼만 가져온다
data.describe()
type(data.describe())
data.describe().T # pd는 np기반이라서 기능 사용가능
#기본적으로 숫자형 데이터만 분석
data.describe(include=['object'])
data.describe(include=['float64', 'object'])
#includr옵션을 사용하면 다른 분석할 데이터 타입을 지정가능


In [ ]:
data.describe(include='O')
#O  대문자 O 
np.number
data.describe(include=np.number)
data.describe(include='all')#모든 데이터 타입을 분석할려면 all 사용


In [80]:
#day컬럼 요소갯수 244
import numpy.ma as ma
data['day'].values.size

data['day'].value_counts()
data['sex'].value_counts()

#평일 고객수와 주말 고객수 합계
a = (data['day']=='Sat') | (data['day']=='Sun')
a.value_counts()

True     163
False     81
Name: day, dtype: int64

In [60]:
b= data['day'].isin({'Sun', 'Sat'})
b.value_counts
#같은 컬럼에 있는 값을 가지고 검색할때 isin을 사용가능
b.unique()

<bound method IndexOpsMixin.value_counts of 0       True
1       True
2       True
3       True
4       True
       ...  
239     True
240     True
241     True
242     True
243    False
Name: day, Length: 244, dtype: bool>

In [65]:
#where
a = np.array([10,20,30,40])
a
np.where(a>30)
#인자는 조건이다 조건만 넣을 경우 참의 위치를 리턴

(array([3]),)

In [72]:
from pandas.core import describe
np.where(a>30,0,100)
# where 인자 갯수에 까라 기능 달라짐, 조건이 참이면 0 거짓이면 100을 반환
data['tip'].count()
data['tip'].mean()
data['tip'].max()
data['tip'].min()
data['tip'].std()


1.3836381890011822

In [81]:

#describe()결과를 numpy에서 제공하는 함수

#tips데이터셋에서 tup값만 가져옴
kk = np.array(data.values[:,1])
kk



NameError: ignored

In [91]:
ma.count(kk)
ma.std(kk)
#ma.max(kk)
kk.max()
#ma.main(kk)
kk.min()



1.0

이미지[https://d20ohkaloyme4g.cloudfront.net/img/document_thumbnails/1a6ece57021a9e3d434865c963d2ef4a/thumb_1200_927.png]

In [ ]:
#data.head()