<a href="https://colab.research.google.com/github/jasen8651/python001/blob/master/python3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#3차원 이상에서 차원 구분법
import numpy as np
#print하면 array글자는 안보인다. 공백이 그대로 보인다. -> 차원구분가능
b = np.arange(24).reshape(2,3,4)
print(b)

b[1,2]

b[0,1]

b[0,1,3]

b[0]

b[[0],:,:]
#b의 0번째 공간 1번재 행 미만, 열 전체
b[0,:1,:]

#ellipsis 모든것을 의미
b[0,:1,:]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[0, 1, 2, 3]])

In [ ]:

#ellipsis 모든것을 의미
b[0,...] 
b[0,:,:] 

b[0, : , 1]
b[0,...]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])