<a href="https://colab.research.google.com/github/jasen8651/python001/blob/master/%ED%8C%8C%EC%9D%BC_%EC%9D%BD%EA%B8%B0read_write.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#open('파일경로', '모드')
#- 모드
#  - w : 쓰기모드 - 파일에 내용을 쓸때 사용
#  - r : 읽기 모드 : 파일 내용을 읽을때사용
#  - a : 추가모드 : 내용을 추가할때 사용

In [3]:
from google.colab import drive
drive.mount('/content/dirve')
%cd /content/dirve/MyDrive/python_demo
!ls

Mounted at /content/dirve
/content/dirve/MyDrive/python_demo
python_01_markdown.ipynb  python_02_basic.ipynb


In [16]:
%%writefile ./gosu2.txt
hello 
ㅎㅇ

Writing ./gosu2.txt


In [ ]:
# 파일형태 2가지 사람기준(txt), 기계기준(binary)
a = open('./gosu.txt','wb')
a.write('hello')
#hello타입은 string이여서 오류 발생 binart로 설정되어있다.


In [11]:
a.write(b'hello')
a.close()

In [18]:
b = open('./gosu2.txt')
next(b)

'hello \n'

In [20]:
b.close()

In [24]:
## wirt구문은 시작할때 enter, 종료할때 __exit를 자동으로 실행해준다 exit가 실행되어 close을 안함
# wirt가 끝난 후 write를 하면 에러 발생
with open('./gosu3.txt', 'wb') as c:
  c.write(b'aaa')
  c.write(b'bbb')

In [ ]:
with open('./gosu3.txt', 'wb') as c:
  print(c.read())

In [29]:
import numpy as np

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
#np의 데이터를 퍼알애 저장 
np.save('.ndata1.',a)

In [ ]:
b = np.load('./ndata1.npy')
b

In [40]:
b = np.array([1,2,3,4,5])
c = np.array([6,7,8,9,10])

np.savez('./ndata2',b,c)

In [49]:
d = np.load('./ndata2.npz')
d
type(b)

dir(d)
#diction 방식으로 저장된 객체를 가져올수 있다
d.files
print(d['arr_0'])
print(d['arr_1'])


[1 2 3 4 5]
[ 6  7  8  9 10]


In [53]:
import pandas as pd

num = np.array([[1,2,3,4],[4,5,6]])
my_df = pd.DataFrame(num)
my_df

<ipython-input-53-0d7e87666b54>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  num = np.array([[1,2,3,4],[4,5,6]])


0
0  [1, 2, 3, 4]
1     [4, 5, 6]

In [58]:
a =my_df.to_csv('./ndata.csv', sep=',')
print(a)

None


In [60]:
a =pd.read_csv('./ndata.csv')
a

Unnamed: 0             0
0           0  [1, 2, 3, 4]
1           1     [4, 5, 6]